@startuml
'https://plantuml.com/state-diagram
'!theme sunlust
!theme blueprint

title 
    Monster Hunter inspired
    Controller Item-selecting
end title

hide empty description

state idle
state selecting

[*] --> idle
idle --> selecting : right joystick leave deadzone
selecting --> idle : right joystick back to deadzone

@enduml