@startuml
'https://plantuml.com/state-diagram
'!theme sunlust
!theme blueprint

title 
    Monster Hunter inspired
    Controller Item-selecting
end title

hide empty description

state idle
state selecting
state "ready to select" as ready

[*] --> idle
idle --> ready : device ready pressed
ready --> idle : device ready released
ready --> selecting : device input above threshold
selecting --> idle : device input below threshold \n or device ready released

@enduml