@startuml
'https://plantuml.com/state-diagram

hide empty description

state idle
state dragging

[*] -> idle

idle --> dragging : left mouse pressed in area

dragging --> idle : left mouse released

@enduml
