@startuml
'https://plantuml.com/state-diagram

hide empty description

state idle
state dragging
state selected

[*] --> idle

idle --> selected : mouse click on area

selected --> dragging : mouse move

selected --> idle : mouse release

dragging --> idle : mouse release

@enduml
